package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/joelysondavid/cv-manager/graph/model"
)

// CreatePerson is the resolver for the createPerson field.
func (r *mutationResolver) CreatePerson(ctx context.Context, input model.CreatePersonInput) (*model.Person, error) {
	panic(fmt.Errorf("not implemented: CreatePerson - createPerson"))
}

// Persons is the resolver for the persons field.
func (r *queryResolver) Persons(ctx context.Context) ([]*model.Person, error) {
	person := &model.Person{
		ID:     "id-01",
		Name:   "Person 01",
		Age:    15,
		IsMale: false,
	}

	persons := []*model.Person{
		person,
	}

	return persons, nil
	panic(fmt.Errorf("not implemented: Persons - persons"))
}
